### ISSUE TITLE
asyncio_mqtt update and retry error

### ISSUE THREAD

**Issue by troyweber** [markusressel/barcode-server#234]
On a clean install on Debian, I receive the following warning on startup: 

2024-05-28 03:14:02,383 - mqtt - WARNING - We renamed asyncio-mqtt to aiomqtt and released a version 1.0.0 in the process. This is the last release under the asyncio-mqtt name. You can find the new repository at https://github.com/sbtinstruments/aiomqtt

When scanning a barcode, I then get this error:

AttributeError: 'Client' object has no attribute 'message_retry_set'
2024-05-28 03:13:11,357 - barcode_server.notifier - ERROR - 'Client' object has no attribute 'message_retry_set'
Traceback (most recent call last):
  File "/home/troy/venv/lib/python3.11/site-packages/barcode_server/notifier/__init__.py", line 81, in event_processor
    await self._send_event(event)
  File "/home/troy/venv/lib/python3.11/site-packages/prometheus_async/aio/_decorators.py", line 67, in time_decorator
    rv = await wrapped(*args, **kw)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/troy/venv/lib/python3.11/site-packages/barcode_server/notifier/mqtt.py", line 34, in _send_event
    async with Client(hostname=self.host, port=self.port,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/troy/venv/lib/python3.11/site-packages/asyncio_mqtt/client.py", line 349, in __init__
    self._client.message_retry_set(message_retry_set)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

On a previous install of this, I forced a bunch of older versions and got everything to run. I am hoping that this is an easy update to the code for you to resolve!

**Comment by markusressel** [comment]
Hi @troyweber thx for the report.
I will take a look asap, should be a quick fix.

**Comment by markusressel** [comment]
Please try again with v2.4.1 , report back if you are still having issues.

**Comment by troyweber** [comment]
You are the best, I can confirm issue resolved!
