### ISSUE TITLE
Installation process failed

### ISSUE THREAD

**Issue by 3FanYu** [markusressel/barcode-server#51]
I followed the How To Use procedures and used the native method in README.md file.
but is getting this error:
```linux=
Traceback (most recent call last):
  File "./venv/bin/barcode-server", line 8, in <module>
    sys.exit(cli())
  File "/home/deploy/monopass/venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/deploy/monopass/venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/deploy/monopass/venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/deploy/monopass/venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/deploy/monopass/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/deploy/monopass/venv/lib/python3.8/site-packages/barcode_server/cli.py", line 84, in c_run
    config = AppConfig()
  File "/home/deploy/monopass/venv/lib/python3.8/site-packages/barcode_server/config.py", line 44, in __new__
    return super(AppConfig, cls).__new__(cls, data_sources=data_sources)
  File "/home/deploy/monopass/venv/lib/python3.8/site-packages/container_app_conf/__init__.py", line 86, in __new__
    self.load_config(validate)
  File "/home/deploy/monopass/venv/lib/python3.8/site-packages/container_app_conf/__init__.py", line 101, in load_config
    self.validate()
  File "/home/deploy/monopass/venv/lib/python3.8/site-packages/barcode_server/config.py", line 236, in validate
    super(AppConfig, self).validate()
  File "/home/deploy/monopass/venv/lib/python3.8/site-packages/container_app_conf/__init__.py", line 109, in validate
    entry.value = entry.value
  File "/home/deploy/monopass/venv/lib/python3.8/site-packages/container_app_conf/entry/__init__.py", line 85, in value
    self._value = self._parse_value(new_value)
  File "/home/deploy/monopass/venv/lib/python3.8/site-packages/container_app_conf/entry/__init__.py", line 97, in _parse_value
    self._raise_invalid_value(value, "Value is required")
  File "/home/deploy/monopass/venv/lib/python3.8/site-packages/container_app_conf/entry/__init__.py", line 137, in _raise_invalid_value
    raise ValueError(message)
ValueError: Invalid value 'None' for config option `barcode_server>server>api_token`: Value is required
```

Are there any steps I missed?

**Comment by markusressel** [comment]
I guess you already know, but you need to configure it before running it. The Readme isnt very clear about that, I will try to improve this.

**Comment by markusressel** [comment]
Oh and also, the api token should be optional, I need to check this as well.
