### ISSUE TITLE
'InputEvent' object has no attribute 'keystate'

### ISSUE THREAD

**Issue by PurpleLobster** [markusressel/barcode-server#85]
I tried setting up the server v2.2.1 via the native method. After adding the udev rules the usbscanner was detected.
Scanning a code results in the following error:

```
2022-01-28 23:09:47,601 - barcode_server - INFO - === barcode-server ===
2022-01-28 23:09:47,602 - barcode_server - INFO - Instance ID: cash-register-1
2022-01-28 23:09:47,623 - barcode_server - INFO - Starting statistics webserver...
2022-01-28 23:09:47,625 - barcode_server.webserver - DEBUG - Starting notifier: http
2022-01-28 23:09:47,625 - barcode_server.webserver - DEBUG - Starting notifier: mqtt
2022-01-28 23:09:47,625 - barcode_server.webserver - INFO - Starting webserver on 127.0.0.1:9654 ...
2022-01-28 23:09:47,631 - barcode_server.barcode - INFO - Reading: /dev/input/event21: Name: Manufacturer Barcode Read
er, Vendor: e851, Product: 1000
2022-01-28 23:09:49,635 - barcode_server.barcode - ERROR - 'InputEvent' object has no attribute 'keystate'
Traceback (most recent call last):
  File "myfolder/barcode-server/venv/lib/python3.8/site-packages/barcode_server/barcode.py", line 94,
 in _start_reader
    barcode = await self._read_line(input_device)
  File "myfolder/barcode-server/venv/lib/python3.8/site-packages/barcode_server/barcode.py", line 152
, in _read_line
    result = await loop.run_in_executor(None, self._keyevent_reader.read_line, input_device)
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "myfolder/barcode-server/venv/lib/python3.8/site-packages/barcode_server/keyevent_reader.py", 
line 60, in read_line
    event.keystate = event.event.keystate
AttributeError: 'InputEvent' object has no attribute 'keystate'
2022-01-28 23:09:49,680 - barcode_server.barcode - INFO - Reading: /dev/input/event21: Name: Manufacturer Barcode Read
er, Vendor: e851, Product: 1000
2022-01-28 23:09:49,683 - barcode_server.barcode - ERROR - 'InputEvent' object has no attribute 'keystate'
Traceback (most recent call last):
  File "myfolder/barcode-server/venv/lib/python3.8/site-packages/barcode_server/barcode.py", line 94,
 in _start_reader
    barcode = await self._read_line(input_device)
  File "myfolder/barcode-server/venv/lib/python3.8/site-packages/barcode_server/barcode.py", line 152
, in _read_line
    result = await loop.run_in_executor(None, self._keyevent_reader.read_line, input_device)
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "myfolder/barcode-server/venv/lib/python3.8/site-packages/barcode_server/keyevent_reader.py", 
line 60, in read_line
    event.keystate = event.event.keystate
AttributeError: 'InputEvent' object has no attribute 'keystate'
2022-01-28 23:09:50,693 - barcode_server.barcode - INFO - Reading: /dev/input/event21: Name: Manufacturer Barcode Read
er, Vendor: e851, Product: 1000
^C2022-01-28 23:09:53,556 - barcode_server.cli - INFO - Exiting...
```
It seems the input device event object is missing the 'keystate' attribute. 

Going back to version 2.0.0 is able to detect the code but gives a different error:

```
2022-01-28 23:01:50,138 - barcode_server.cli - INFO - Starting statistics webserver...
2022-01-28 23:01:50,139 - barcode_server.webserver - DEBUG - Starting notifier: http
2022-01-28 23:01:50,139 - barcode_server.webserver - DEBUG - Starting notifier: mqtt
2022-01-28 23:01:50,139 - barcode_server.webserver - INFO - Starting webserver on 127.0.0.1:9654 ...
2022-01-28 23:01:50,146 - barcode_server.barcode - INFO - Reading: /dev/input/event21: Name: Manufacturer Barcode Reader, Vendor: e851, Product: 1000
2022-01-28 23:01:53,158 - barcode_server.keyevent_reader - DEBUG - key event at 1643407313.157973, 10 (KEY_9), down
2022-01-28 23:01:53,166 - barcode_server.keyevent_reader - DEBUG - key event at 1643407313.166009, 10 (KEY_9), up
2022-01-28 23:01:53,166 - barcode_server.keyevent_reader - DEBUG - key event at 1643407313.166009, 8 (KEY_7), down
2022-01-28 23:01:53,174 - barcode_server.keyevent_reader - DEBUG - key event at 1643407313.173921, 8 (KEY_7), up
2022-01-28 23:01:53,174 - barcode_server.keyevent_reader - DEBUG - key event at 1643407313.173921, 9 (KEY_8), down
2022-01-28 23:01:53,181 - barcode_server.keyevent_reader - DEBUG - key event at 1643407313.181903, 9 (KEY_8), up
2022-01-28 23:01:53,182 - barcode_server.keyevent_reader - DEBUG - key event at 1643407313.181903, 10 (KEY_9), down
2022-01-28 23:01:53,190 - barcode_server.keyevent_reader - DEBUG - key event at 1643407313.189930, 10 (KEY_9), up
2022-01-28 23:01:53,190 - barcode_server.keyevent_reader - DEBUG - key event at 1643407313.189930, 5 (KEY_4), down
2022-01-28 23:01:53,198 - barcode_server.keyevent_reader - DEBUG - key event at 1643407313.197941, 5 (KEY_4), up
2022-01-28 23:01:53,198 - barcode_server.keyevent_reader - DEBUG - key event at 1643407313.197941, 7 (KEY_6), down
2022-01-28 23:01:53,207 - barcode_server.keyevent_reader - DEBUG - key event at 1643407313.206992, 7 (KEY_6), up
2022-01-28 23:01:53,208 - barcode_server.keyevent_reader - DEBUG - key event at 1643407313.206992, 3 (KEY_2), down
2022-01-28 23:01:53,215 - barcode_server.keyevent_reader - DEBUG - key event at 1643407313.215003, 3 (KEY_2), up
2022-01-28 23:01:53,216 - barcode_server.keyevent_reader - DEBUG - key event at 1643407313.215003, 10 (KEY_9), down
2022-01-28 23:01:53,223 - barcode_server.keyevent_reader - DEBUG - key event at 1643407313.222966, 10 (KEY_9), up
2022-01-28 23:01:53,223 - barcode_server.keyevent_reader - DEBUG - key event at 1643407313.222966, 9 (KEY_8), down
2022-01-28 23:01:53,231 - barcode_server.keyevent_reader - DEBUG - key event at 1643407313.230930, 9 (KEY_8), up
2022-01-28 23:01:53,231 - barcode_server.keyevent_reader - DEBUG - key event at 1643407313.230930, 5 (KEY_4), down
2022-01-28 23:01:53,239 - barcode_server.keyevent_reader - DEBUG - key event at 1643407313.238904, 5 (KEY_4), up
2022-01-28 23:01:53,239 - barcode_server.keyevent_reader - DEBUG - key event at 1643407313.238904, 2 (KEY_1), down
2022-01-28 23:01:53,247 - barcode_server.keyevent_reader - DEBUG - key event at 1643407313.246976, 2 (KEY_1), up
2022-01-28 23:01:53,247 - barcode_server.keyevent_reader - DEBUG - key event at 1643407313.246976, 5 (KEY_4), down
2022-01-28 23:01:53,255 - barcode_server.keyevent_reader - DEBUG - key event at 1643407313.254961, 5 (KEY_4), up
2022-01-28 23:01:53,255 - barcode_server.keyevent_reader - DEBUG - key event at 1643407313.254961, 2 (KEY_1), down
2022-01-28 23:01:53,264 - barcode_server.keyevent_reader - DEBUG - key event at 1643407313.263919, 2 (KEY_1), up
2022-01-28 23:01:53,264 - barcode_server.keyevent_reader - DEBUG - key event at 1643407313.263919, 28 (KEY_ENTER), down
2022-01-28 23:01:53,272 - barcode_server.keyevent_reader - DEBUG - key event at 1643407313.272001, 28 (KEY_ENTER), up
2022-01-28 23:01:53,273 - barcode_server.barcode - INFO - Manufacturer Barcode Reader (/dev/input/event21): 9789462984141
2022-01-28 23:01:53,387 - barcode_server.notifier - ERROR - [Errno -2] Name or service not known
Traceback (most recent call last):
  File "myfolder/barcode-server-2.0.0/venv/lib/python3.8/site-packages/asyncio_mqtt-0.9.1-py3.8.egg/asyncio_mqtt/client.py", line 173, in connect
    await loop.run_in_executor(
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "myfolder/barcode-server-2.0.0/venv/lib/python3.8/site-packages/paho_mqtt-1.5.1-py3.8.egg/paho/mqtt/client.py", line 941, in connect
    return self.reconnect()
  File "myfolder/barcode-server-2.0.0/venv/lib/python3.8/site-packages/paho_mqtt-1.5.1-py3.8.egg/paho/mqtt/client.py", line 1075, in reconnect
    sock = self._create_socket_connection()
  File "myfolder/barcode-server-2.0.0/venv/lib/python3.8/site-packages/paho_mqtt-1.5.1-py3.8.egg/paho/mqtt/client.py", line 3546, in _create_socket_connection
    return socket.create_connection(addr, source_address=source, timeout=self._keepalive)
  File "/usr/lib/python3.8/socket.py", line 787, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "myfolder/barcode-server-2.0.0/venv/lib/python3.8/site-packages/barcode_server-2.0.0-py3.8.egg/barcode_server/notifier/__init__.py", line 81, in event_processor
    await self._send_event(event)
  File "myfolder/barcode-server-2.0.0/venv/lib/python3.8/site-packages/prometheus_async-19.2.0-py3.8.egg/prometheus_async/aio/_decorators.py", line 42, in time_decorator
    rv = await wrapped(*args, **kw)
  File "myfolder/barcode-server-2.0.0/venv/lib/python3.8/site-packages/barcode_server-2.0.0-py3.8.egg/barcode_server/notifier/mqtt.py", line 34, in _send_event
    async with Client(hostname=self.host, port=self.port,
  File "myfolder/barcode-server-2.0.0/venv/lib/python3.8/site-packages/asyncio_mqtt-0.9.1-py3.8.egg/asyncio_mqtt/client.py", line 512, in __aenter__
    await self.connect()
  File "myfolder/barcode-server-2.0.0/venv/lib/python3.8/site-packages/asyncio_mqtt-0.9.1-py3.8.egg/asyncio_mqtt/client.py", line 184, in connect
    raise MqttError(str(error))
asyncio_mqtt.error.MqttError: [Errno -2] Name or service not known
2022-01-28 23:01:54,022 - barcode_server.notifier.http - DEBUG - Notified http://dummy.restapiexample.com/api/v1/create: 9789462984141
2022-01-28 23:01:55,496 - barcode_server.notifier - ERROR - [Errno -2] Name or service not known
Traceback (most recent call last):
  File "myfolder/barcode-server-2.0.0/venv/lib/python3.8/site-packages/asyncio_mqtt-0.9.1-py3.8.egg/asyncio_mqtt/client.py", line 173, in connect
    await loop.run_in_executor(
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "myfolder/barcode-server-2.0.0/venv/lib/python3.8/site-packages/paho_mqtt-1.5.1-py3.8.egg/paho/mqtt/client.py", line 941, in connect
    return self.reconnect()
  File "myfolder/barcode-server-2.0.0/venv/lib/python3.8/site-packages/paho_mqtt-1.5.1-py3.8.egg/paho/mqtt/client.py", line 1075, in reconnect
    sock = self._create_socket_connection()
  File "myfolder/barcode-server-2.0.0/venv/lib/python3.8/site-packages/paho_mqtt-1.5.1-py3.8.egg/paho/mqtt/client.py", line 3546, in _create_socket_connection
    return socket.create_connection(addr, source_address=source, timeout=self._keepalive)
  File "/usr/lib/python3.8/socket.py", line 787, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "myfolder/barcode-server-2.0.0/venv/lib/python3.8/site-packages/barcode_server-2.0.0-py3.8.egg/barcode_server/notifier/__init__.py", line 81, in event_processor
    await self._send_event(event)
  File "myfolder/barcode-server-2.0.0/venv/lib/python3.8/site-packages/prometheus_async-19.2.0-py3.8.egg/prometheus_async/aio/_decorators.py", line 42, in time_decorator
    rv = await wrapped(*args, **kw)
  File "myfolder/barcode-server-2.0.0/venv/lib/python3.8/site-packages/barcode_server-2.0.0-py3.8.egg/barcode_server/notifier/mqtt.py", line 34, in _send_event
    async with Client(hostname=self.host, port=self.port,
  File "myfolder/barcode-server-2.0.0/venv/lib/python3.8/site-packages/asyncio_mqtt-0.9.1-py3.8.egg/asyncio_mqtt/client.py", line 512, in __aenter__
    await self.connect()
  File "myfolder/barcode-server-2.0.0/venv/lib/python3.8/site-packages/asyncio_mqtt-0.9.1-py3.8.egg/asyncio_mqtt/client.py", line 184, in connect
    raise MqttError(str(error))
asyncio_mqtt.error.MqttError: [Errno -2] Name or service not known
^C2022-01-28 23:01:56,942 - barcode_server.cli - INFO - Exiting...
```

Any suggestions?

**Comment by markusressel** [comment]
Recent changes have introduced some bugs into the code that I was unable to test. I have made some changes to hopefully fix this in the latest release.

The second error indicates that barcode-server cannot reach your MQTT server.
This can have many reasons: firewall, access permissions, network configuration...

**Comment by PurpleLobster** [comment]
Issue solved, thanks! 
Love the library! :+1:
